name: ngekas
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.0-271.4.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
  fonts:
    - family: fredoka
      fonts:
        - asset: "assets/fonts/Fredoka/static/Fredoka/Fredoka-Regular.ttf"

    - family: fredoka_medium
      fonts:
        - asset: "assets/fonts/Fredoka/static/Fredoka/Fredoka-Medium.ttf"

    - family: fredoka-one
      fonts:
        - asset: "assets/fonts/Fredoka_One/FredokaOne-Regular.ttf"

    - family: roboto_slab
      fonts:
        - asset: "assets/fonts/Roboto_Slab/static/RobotoSlab-Regular.ttf"

    - family: varela
      fonts:
        - asset: "assets/fonts/Varela/Varela-Regular.ttf"

    - family: varela_round
      fonts:
        - asset: "assets/fonts/Varela_Round/VarelaRound-Regular.ttf"

    - family: noto_sans_semibold
      fonts:
        - asset: "assets/fonts/Noto_Sans/NotoSans-SemiBold.ttf"

    - family: noto_sans
      fonts:
        - asset: "assets/fonts/Noto_Sans/NotoSans-Regular.ttf"

    - family: noto_sans_medium
      fonts:
        - asset: "assets/fonts/Noto_Sans/NotoSans-Medium.ttf"

    - family: noto_sans_bold_italic
      fonts:
        - asset: "assets/fonts/Noto_Sans/NotoSans-BoldItalic.ttf"
